language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator10.0
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail
- pod lib lint --allow-warnings
